import type { Company, CompanyRow } from "./company.types";

export const userId = "11111111-1111-4111-8111-111111111111";
export const companyId = "22222222-2222-4222-8222-222222222222";

export const companyRowFixture: CompanyRow = {
  id: companyId,
  legal_name: "ABC (Malaysia), Sdn Bhd",
  display_name: "ABC (Malaysia)",
  company_type: "fnb",
  industry: "Food & Beverage",
  description: "Restaurant group",
  public_phone: "6041234567",
  public_email: "hello@example.my",
  website_url: "https://www.example.my/menu",
  website_domain: "example.my",
  facebook_url: null,
  instagram_url: "https://instagram.com/example",
  tiktok_url: null,
  youtube_url: null,
  google_maps_url: null,
  address_line_1: "1 Jalan Example",
  address_line_2: null,
  city: "George Town",
  state: "Penang",
  postcode: "10000",
  country: "MY",
  estimated_branch_count: 3,
  source_url: "https://example.my/contact",
  source_type: "company_website",
  discovered_at: "2026-07-12T00:00:00.000Z",
  last_verified_at: null,
  created_by: userId,
  created_at: "2026-07-12T00:00:00.000Z",
  updated_at: "2026-07-12T00:00:00.000Z",
  fingerprint: "0123456789abcdef0123456789abcdef",
  deleted_at: null,
};

export const companyFixture: Company = {
  id: companyRowFixture.id,
  legalName: companyRowFixture.legal_name,
  displayName: companyRowFixture.display_name,
  companyType: companyRowFixture.company_type,
  industry: companyRowFixture.industry,
  description: companyRowFixture.description,
  publicPhone: companyRowFixture.public_phone,
  publicEmail: companyRowFixture.public_email,
  websiteUrl: companyRowFixture.website_url,
  websiteDomain: companyRowFixture.website_domain,
  facebookUrl: companyRowFixture.facebook_url,
  instagramUrl: companyRowFixture.instagram_url,
  tiktokUrl: companyRowFixture.tiktok_url,
  youtubeUrl: companyRowFixture.youtube_url,
  googleMapsUrl: companyRowFixture.google_maps_url,
  addressLine1: companyRowFixture.address_line_1,
  addressLine2: companyRowFixture.address_line_2,
  city: companyRowFixture.city,
  state: companyRowFixture.state,
  postcode: companyRowFixture.postcode,
  country: companyRowFixture.country,
  estimatedBranchCount: companyRowFixture.estimated_branch_count,
  sourceUrl: companyRowFixture.source_url,
  sourceType: companyRowFixture.source_type,
  discoveredAt: companyRowFixture.discovered_at,
  lastVerifiedAt: companyRowFixture.last_verified_at,
  createdBy: companyRowFixture.created_by,
  createdAt: companyRowFixture.created_at,
  updatedAt: companyRowFixture.updated_at,
  fingerprint: companyRowFixture.fingerprint,
  deletedAt: companyRowFixture.deleted_at,
};
